### ISSUE TITLE
rJava

### ISSUE THREAD

**Issue by mattfidler** [krlmlr/r-appveyor#85] opened 2017-01-30 04:12 UTC
I am having problems using rJava on certain systems.  I get errors like:

```
  Error: .onLoad failed in loadNamespace() for 'rJava', details:
    call: inDL(x, as.logical(local), as.logical(now), ...)
    error: unable to load shared object 'C:/Users/appveyor/AppData/Local/Temp/1/RtmpWa3KNC/RLIBS_bdc2913935/rJava/libs/i386/rJava.dll':
    LoadLibrary failure:  %1 is not a valid Win32 application.
```

Apparently,  there are some issues using rJava on Windows anyway; See:

http://stackoverflow.com/questions/7019912/using-the-rjava-package-on-win7-64-bit-with-r

Is there any information about how appveyor installs the java environment?

**Comment by krlmlr** [comment] 2017-03-20 22:06
Is this a mismatch between 32-bit and 64-bit architectures? I don't have any experience with rJava, but the error looks independent of the Jave environment.

**Comment by mattfidler** [comment] 2017-03-21 00:29
I'm not really sure myself, unfortunately.

**Comment by rplzzz** [comment] 2017-09-22 19:59
FWIW, I am also having this issue, with more or less the same error message.  From what I've been able to tell, the problem seems to be caused by running a 32-bit version of R, which does seem to be what is happening:
```
* using log directory 'C:/projects/iamrpt/iamrpt.Rcheck'
* using R version 3.4.1 Patched (2017-09-16 r73293)
* using platform: i386-w64-mingw32 (32-bit)
```

So, it looks like we need to specify that the R version needs to be 64-bit.  Setting `Platform: x64` in `appveyor.yml` doesn't do the trick; it gets you a 64-bit host, but you still get the 32-bit version of R.

Thoughts?

**Comment by rplzzz** [comment] 2017-09-22 20:39
Installing 64-bit R using `R_ARCH` did the trick.  So, if you landed on this issue because you're getting this error, your fix is to add the following to `appveyor.yml`:
```
platform: x64

environment:
  R_ARCH: x64
```

**Comment by krlmlr** [comment] 2017-09-24 07:41
@rplzzz: Thanks for looking into it. Would you like to submit a PR that adds this information to the README?

**Comment by rplzzz** [comment] 2017-09-24 12:36
Sure, happy to.

**Closed** 2017-12-07 08:06 UTC

**Comment by MansMeg** [comment] 2018-03-09 11:40
Hi all!

I still have the same problem. I get:

```
Error: package or namespace load failed for 'mallet':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/appveyor/AppData/Local/Temp/1/RtmpgdOTOJ/RLIBS_89876f6184f/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.
```

With both:
```
* using log directory 'C:/projects/rmallet/mallet.Rcheck'
* using R version 3.4.3 Patched (2018-03-02 r74345)
* using platform: i386-w64-mingw32 (32-bit)
```
and with
```
* using log directory 'C:/projects/rmallet/mallet.Rcheck'
* using R version 3.4.3 Patched (2018-03-02 r74345)
* using platform: x86_64-w64-mingw32 (64-bit)
```

Here is the appveyor run:
https://ci.appveyor.com/project/MansMeg/rmallet

And the codebase/appveyor file:
https://github.com/MansMeg/RMallet

**Comment by krlmlr** [comment] 2018-03-22 00:00
@MansMeg: The error for x64 in the artifacts of your most recent AppVeyor build looks different from the i386 error.

**Comment by MansMeg** [comment] 2018-03-28 13:48
Yes. It does. I can't really what is the problem?

**Comment by krlmlr** [comment] 2018-03-28 14:25
Maybe *rJava* doesn't work on i386? The x64 builds looked better to me -- not like a failure to install *rJava* but a different problem.

**Comment by GregorDeCillia** [comment] 2019-05-26 17:09
I am still getting the issue of 

    LoadLibrary failure:  %1 is not a valid Win32 application.

even after specifying `platform` and `environment` as mentioned in the troubleshooting section of the README. My logs state clearly, that a 64-bit version of R is used

```
+ R CMD check styledTables_2.1.0.tar.gz --no-manual --as-cran --install-args=--build
* using log directory 'C:/projects/styledtables/styledTables.Rcheck'
* using R version 3.6.0 Patched (2019-05-24 r76596)
* using platform: x86_64-w64-mingw32 (64-bit)
```

The full log can be examined [here](https://ci.appveyor.com/project/GregorDeCillia/styledtables). More diagnostics can be found in the artifact `failure.zip`. For example `00install.out` reads

<details>

<summary> <code>00install.out</code> </summary>

```
* installing *source* package 'styledTables' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'styledTables':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/appveyor/AppData/Local/Temp/1/RtmpeaKgoL/RLIBS_8643b906940/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/projects/styledtables/styledTables.Rcheck/styledTables'
```

</details>

Is this because of `mingw32`? Is there a way to switch to another `mingw` version?
