### ISSUE TITLE
Corruption in installing package dependencies?

### ISSUE THREAD

**Issue by jangorecki** [krlmlr/r-appveyor#71] opened 2016-07-01 12:47 UTC
Looks like there is some corruption in the build environment.
In the [following build](https://ci.appveyor.com/project/jangorecki/data-table/build/1.0.75) I had installed knitr:
```
Installing 1 package: knitr
Installing package into 'c:/RLibrary'
(as 'lib' is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/knitr_1.13.zip'
Content type 'application/zip' length 861084 bytes (840 KB)
==================================================
downloaded 840 KB
package 'knitr' successfully unpacked and MD5 sums checked
```
While it appears knitr mandatory dep stringr haven't been installed
```
* checking tests ...
...
  Running 'knitr.R'
Warning message:
running command '"c:/R/bin/i386/R" CMD BATCH --vanilla  "knitr.R" "knitr.Rout"' had status 1 
 ERROR
Running the tests in 'tests/knitr.R' failed.
...
  Loading required package: knitr
  Warning: namespace 'evaluate' is not available and has been replaced
  by .GlobalEnv when processing object ''
  Warning: namespace 'evaluate' is not available and has been replaced
  by .GlobalEnv when processing object ''
  Error in loadNamespace(name) : there is no package called 'stringr'
```
There  is no attempt to install stringr anywhere in the log.

**Comment by krlmlr** [comment] 2016-07-01 13:22
Duplicate of #69?

**Closed by krlmlr** 2016-07-01 13:22 UTC
