### ISSUE TITLE
recent build error: "there is no package called 'Rcpp'"

### ISSUE THREAD

**Issue by mdlincoln** [krlmlr/r-appveyor#70] opened 2016-06-26 02:13 UTC
I've encountered a new build error on a package that has had no such issues before:

```
...
* checking examples ... ERROR
Running examples in 'fuzzr-Ex.R' failed
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: fuzz_function
> ### Title: Fuzz-test a function
> ### Aliases: fuzz_function p_fuzz_function
> 
> ### ** Examples
> 
> # Evaluate the 'formula' argument of lm, passing additional required variables
> fuzz_function(lm, "formula", data = iris)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
Calls: fuzz_function ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
...
```

[Full log here.](https://ci.appveyor.com/project/mdlincoln/fuzzr/build/1.0.20#L430)

This was perplexing given that no errors were raised during the installation of dependencies. The same code built with no errors or warnings on win builder. Any insights?

**Comment by krlmlr** [comment] 2016-06-26 06:04
Weird. This could be a transitional error caused by R 3.3.1, please ping me if the error still occurs in two days.

**Comment by ateucher** [comment] 2016-06-26 06:45
I'm getting the same error:

```
* checking whether package 'rmapshaper' can be installed ...Warning: running command '"c:/R/bin/i386/Rcmd.exe" INSTALL -l "C:/projects/rmapshaper/rmapshaper.Rcheck" --build --no-html --no-multiarch "C:\projects\RMAPSH~1\RMAPSH~1.RCH\00_PKG~1\RMAPSH~1"' had status 1
 ERROR
Installation failed.
See 'C:/projects/rmapshaper/rmapshaper.Rcheck/00install.out' for details.
* DONE
Status: 1 ERROR
See
  'C:/projects/rmapshaper/rmapshaper.Rcheck/00check.log'
for details.
Command exited with code 1
7z a failure.zip *.Rcheck\*
```

The full log of min is [here](https://ci.appveyor.com/project/ateucher/rmapshaper/build/1.0.44#L428). 

It is building fine on my Mac, on Travis, and on win-builder.

**Comment by krlmlr** [comment] 2016-06-26 10:42
@ateucher: Not sure this is the same problem. Anyway, you can download a zip file of the check directory under "Artifacts", this might help troubleshoot the issue.

**Comment by ateucher** [comment] 2016-06-26 17:59
Thanks @krlmlr, I should have posted the contents of `000install.out` from "Artifacts". Here it is:

```
* installing *source* package 'rmapshaper' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'rmapshaper'
* removing 'C:/projects/rmapshaper/rmapshaper.Rcheck/rmapshaper'
```

I thought it might be related to @mdlincoln's issue as the error is very similar, though they do occur under different circumstances. My package does not import `Rcpp` directly, but does require a package that does (`V8`) - and I think the same is true with @mdlincoln's `fuzzr`.

**Comment by krlmlr** [comment] 2016-06-26 20:49
Now it makes sense. Let's wait and see if these issues persist.

**Comment by krlmlr** [comment] 2016-07-01 09:46
I'm now pretty sure this is a dupe of #69, and the root cause is https://github.com/hadley/devtools/issues/1246.

**Closed by krlmlr** 2016-07-01 09:46 UTC
